name: Release drafter
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  # write permission is required to create a github release
  contents: write
  # write permission is required for autolabeler
  # otherwise, read permission is required at least
  pull-requests: write

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

